DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS videos CASCADE;
DROP TABLE IF EXISTS faces CASCADE;
DROP TABLE IF EXISTS visits CASCADE;
DROP TABLE IF EXISTS traffic CASCADE;
DROP TABLE IF EXISTS persons CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  s3_image VARCHAR(255)
);

CREATE TABLE videos (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  duration INTEGER NOT NULL,
  uploaded_at TIMESTAMP,
  started_at TIMESTAMP, 
  is_analyzed BOOLEAN DEFAULT FALSE,
  s3_url VARCHAR(255),
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE faces (
  id SERIAL PRIMARY KEY NOT NULL,
  faceId VARCHAR(255) NOT NULL,
  gender BOOLEAN NOT NULL,
  ageRange INTEGER NOT NULL,
  externalId VARCHAR(255),
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE visits (
  id SERIAL PRIMARY KEY NOT NULL,
  time TIMESTAMP NOT NULL,
  emotions INTEGER[],
  smile INTEGER NOT NULL,
  face_id VARCHAR REFERENCES faces(id) ON DELETE CASCADE,
  video_id INTEGER REFERENCES videos(id) ON DELETE CASCADE
);

CREATE TABLE persons (
  id SERIAL PRIMARY KEY NOT NULL,
  show_time TIMESTAMP NOT NULL,
  leave_time TIMESTAMP NOT NULL,
  index INTEGER,
  video_id INTEGER REFERENCES videos(id) ON DELETE CASCADE
);

CREATE TABLE traffic (
  id SERIAL PRIMARY KEY NOT NULL,
  timestamp INTEGER NOT NULL,
  count INTEGER NOT NULL,
  video_id INTEGER REFERENCES videos(id) ON DELETE CASCADE
);